package com.tiger.codec;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginEvent.proto

public final class LoginEventProtobuf {
  private LoginEventProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN = 0;</code>
     */
    LOGIN(0),
    /**
     * <code>LOGOUT = 1;</code>
     */
    LOGOUT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LOGIN = 0;</code>
     */
    public static final int LOGIN_VALUE = 0;
    /**
     * <code>LOGOUT = 1;</code>
     */
    public static final int LOGOUT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return LOGIN;
        case 1: return LOGOUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return LoginEventProtobuf.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageType)
  }

  public interface UserEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.LoginEvent loginEvent = 1;</code>
     * @return Whether the loginEvent field is set.
     */
    boolean hasLoginEvent();
    /**
     * <code>.LoginEvent loginEvent = 1;</code>
     * @return The loginEvent.
     */
    LoginEvent getLoginEvent();
    /**
     * <code>.LoginEvent loginEvent = 1;</code>
     */
    LoginEventOrBuilder getLoginEventOrBuilder();

    /**
     * <code>.LogoutEvent logoutEvent = 2;</code>
     * @return Whether the logoutEvent field is set.
     */
    boolean hasLogoutEvent();
    /**
     * <code>.LogoutEvent logoutEvent = 2;</code>
     * @return The logoutEvent.
     */
    LogoutEvent getLogoutEvent();
    /**
     * <code>.LogoutEvent logoutEvent = 2;</code>
     */
    LogoutEventOrBuilder getLogoutEventOrBuilder();

    /**
     * <code>.MessageType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.MessageType type = 3;</code>
     * @return The type.
     */
    MessageType getType();

    public UserEvent.EventCase getEventCase();
  }
  /**
   * Protobuf type {@code UserEvent}
   */
  public static final class UserEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserEvent)
      UserEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserEvent.newBuilder() to construct.
    private UserEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserEvent() {
      type_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserEvent();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              LoginEvent.Builder subBuilder = null;
              if (eventCase_ == 1) {
                subBuilder = ((LoginEvent) event_).toBuilder();
              }
              event_ =
                  input.readMessage(LoginEvent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((LoginEvent) event_);
                event_ = subBuilder.buildPartial();
              }
              eventCase_ = 1;
              break;
            }
            case 18: {
              LogoutEvent.Builder subBuilder = null;
              if (eventCase_ == 2) {
                subBuilder = ((LogoutEvent) event_).toBuilder();
              }
              event_ =
                  input.readMessage(LogoutEvent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((LogoutEvent) event_);
                event_ = subBuilder.buildPartial();
              }
              eventCase_ = 2;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LoginEventProtobuf.internal_static_UserEvent_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LoginEventProtobuf.internal_static_UserEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserEvent.class, Builder.class);
    }

    private int eventCase_ = 0;
    private Object event_;
    public enum EventCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      LOGINEVENT(1),
      LOGOUTEVENT(2),
      EVENT_NOT_SET(0);
      private final int value;
      private EventCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static EventCase valueOf(int value) {
        return forNumber(value);
      }

      public static EventCase forNumber(int value) {
        switch (value) {
          case 1: return LOGINEVENT;
          case 2: return LOGOUTEVENT;
          case 0: return EVENT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public EventCase
    getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public static final int LOGINEVENT_FIELD_NUMBER = 1;
    /**
     * <code>.LoginEvent loginEvent = 1;</code>
     * @return Whether the loginEvent field is set.
     */
    @Override
    public boolean hasLoginEvent() {
      return eventCase_ == 1;
    }
    /**
     * <code>.LoginEvent loginEvent = 1;</code>
     * @return The loginEvent.
     */
    @Override
    public LoginEvent getLoginEvent() {
      if (eventCase_ == 1) {
         return (LoginEvent) event_;
      }
      return LoginEvent.getDefaultInstance();
    }
    /**
     * <code>.LoginEvent loginEvent = 1;</code>
     */
    @Override
    public LoginEventOrBuilder getLoginEventOrBuilder() {
      if (eventCase_ == 1) {
         return (LoginEvent) event_;
      }
      return LoginEvent.getDefaultInstance();
    }

    public static final int LOGOUTEVENT_FIELD_NUMBER = 2;
    /**
     * <code>.LogoutEvent logoutEvent = 2;</code>
     * @return Whether the logoutEvent field is set.
     */
    @Override
    public boolean hasLogoutEvent() {
      return eventCase_ == 2;
    }
    /**
     * <code>.LogoutEvent logoutEvent = 2;</code>
     * @return The logoutEvent.
     */
    @Override
    public LogoutEvent getLogoutEvent() {
      if (eventCase_ == 2) {
         return (LogoutEvent) event_;
      }
      return LogoutEvent.getDefaultInstance();
    }
    /**
     * <code>.LogoutEvent logoutEvent = 2;</code>
     */
    @Override
    public LogoutEventOrBuilder getLogoutEventOrBuilder() {
      if (eventCase_ == 2) {
         return (LogoutEvent) event_;
      }
      return LogoutEvent.getDefaultInstance();
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>.MessageType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.MessageType type = 3;</code>
     * @return The type.
     */
    @Override public MessageType getType() {
      @SuppressWarnings("deprecation")
      MessageType result = MessageType.valueOf(type_);
      return result == null ? MessageType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (eventCase_ == 1) {
        output.writeMessage(1, (LoginEvent) event_);
      }
      if (eventCase_ == 2) {
        output.writeMessage(2, (LogoutEvent) event_);
      }
      if (type_ != MessageType.LOGIN.getNumber()) {
        output.writeEnum(3, type_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (eventCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (LoginEvent) event_);
      }
      if (eventCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (LogoutEvent) event_);
      }
      if (type_ != MessageType.LOGIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserEvent)) {
        return super.equals(obj);
      }
      UserEvent other = (UserEvent) obj;

      if (type_ != other.type_) return false;
      if (!getEventCase().equals(other.getEventCase())) return false;
      switch (eventCase_) {
        case 1:
          if (!getLoginEvent()
              .equals(other.getLoginEvent())) return false;
          break;
        case 2:
          if (!getLogoutEvent()
              .equals(other.getLogoutEvent())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      switch (eventCase_) {
        case 1:
          hash = (37 * hash) + LOGINEVENT_FIELD_NUMBER;
          hash = (53 * hash) + getLoginEvent().hashCode();
          break;
        case 2:
          hash = (37 * hash) + LOGOUTEVENT_FIELD_NUMBER;
          hash = (53 * hash) + getLogoutEvent().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserEvent)
        UserEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LoginEventProtobuf.internal_static_UserEvent_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LoginEventProtobuf.internal_static_UserEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserEvent.class, Builder.class);
      }

      // Construct using LoginEventProtobuf.UserEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        eventCase_ = 0;
        event_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LoginEventProtobuf.internal_static_UserEvent_descriptor;
      }

      @Override
      public UserEvent getDefaultInstanceForType() {
        return UserEvent.getDefaultInstance();
      }

      @Override
      public UserEvent build() {
        UserEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UserEvent buildPartial() {
        UserEvent result = new UserEvent(this);
        if (eventCase_ == 1) {
          if (loginEventBuilder_ == null) {
            result.event_ = event_;
          } else {
            result.event_ = loginEventBuilder_.build();
          }
        }
        if (eventCase_ == 2) {
          if (logoutEventBuilder_ == null) {
            result.event_ = event_;
          } else {
            result.event_ = logoutEventBuilder_.build();
          }
        }
        result.type_ = type_;
        result.eventCase_ = eventCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserEvent) {
          return mergeFrom((UserEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserEvent other) {
        if (other == UserEvent.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        switch (other.getEventCase()) {
          case LOGINEVENT: {
            mergeLoginEvent(other.getLoginEvent());
            break;
          }
          case LOGOUTEVENT: {
            mergeLogoutEvent(other.getLogoutEvent());
            break;
          }
          case EVENT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int eventCase_ = 0;
      private Object event_;
      public EventCase
          getEventCase() {
        return EventCase.forNumber(
            eventCase_);
      }

      public Builder clearEvent() {
        eventCase_ = 0;
        event_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          LoginEvent, LoginEvent.Builder, LoginEventOrBuilder> loginEventBuilder_;
      /**
       * <code>.LoginEvent loginEvent = 1;</code>
       * @return Whether the loginEvent field is set.
       */
      @Override
      public boolean hasLoginEvent() {
        return eventCase_ == 1;
      }
      /**
       * <code>.LoginEvent loginEvent = 1;</code>
       * @return The loginEvent.
       */
      @Override
      public LoginEvent getLoginEvent() {
        if (loginEventBuilder_ == null) {
          if (eventCase_ == 1) {
            return (LoginEvent) event_;
          }
          return LoginEvent.getDefaultInstance();
        } else {
          if (eventCase_ == 1) {
            return loginEventBuilder_.getMessage();
          }
          return LoginEvent.getDefaultInstance();
        }
      }
      /**
       * <code>.LoginEvent loginEvent = 1;</code>
       */
      public Builder setLoginEvent(LoginEvent value) {
        if (loginEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          event_ = value;
          onChanged();
        } else {
          loginEventBuilder_.setMessage(value);
        }
        eventCase_ = 1;
        return this;
      }
      /**
       * <code>.LoginEvent loginEvent = 1;</code>
       */
      public Builder setLoginEvent(
          LoginEvent.Builder builderForValue) {
        if (loginEventBuilder_ == null) {
          event_ = builderForValue.build();
          onChanged();
        } else {
          loginEventBuilder_.setMessage(builderForValue.build());
        }
        eventCase_ = 1;
        return this;
      }
      /**
       * <code>.LoginEvent loginEvent = 1;</code>
       */
      public Builder mergeLoginEvent(LoginEvent value) {
        if (loginEventBuilder_ == null) {
          if (eventCase_ == 1 &&
              event_ != LoginEvent.getDefaultInstance()) {
            event_ = LoginEvent.newBuilder((LoginEvent) event_)
                .mergeFrom(value).buildPartial();
          } else {
            event_ = value;
          }
          onChanged();
        } else {
          if (eventCase_ == 1) {
            loginEventBuilder_.mergeFrom(value);
          }
          loginEventBuilder_.setMessage(value);
        }
        eventCase_ = 1;
        return this;
      }
      /**
       * <code>.LoginEvent loginEvent = 1;</code>
       */
      public Builder clearLoginEvent() {
        if (loginEventBuilder_ == null) {
          if (eventCase_ == 1) {
            eventCase_ = 0;
            event_ = null;
            onChanged();
          }
        } else {
          if (eventCase_ == 1) {
            eventCase_ = 0;
            event_ = null;
          }
          loginEventBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.LoginEvent loginEvent = 1;</code>
       */
      public LoginEvent.Builder getLoginEventBuilder() {
        return getLoginEventFieldBuilder().getBuilder();
      }
      /**
       * <code>.LoginEvent loginEvent = 1;</code>
       */
      @Override
      public LoginEventOrBuilder getLoginEventOrBuilder() {
        if ((eventCase_ == 1) && (loginEventBuilder_ != null)) {
          return loginEventBuilder_.getMessageOrBuilder();
        } else {
          if (eventCase_ == 1) {
            return (LoginEvent) event_;
          }
          return LoginEvent.getDefaultInstance();
        }
      }
      /**
       * <code>.LoginEvent loginEvent = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          LoginEvent, LoginEvent.Builder, LoginEventOrBuilder>
          getLoginEventFieldBuilder() {
        if (loginEventBuilder_ == null) {
          if (!(eventCase_ == 1)) {
            event_ = LoginEvent.getDefaultInstance();
          }
          loginEventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              LoginEvent, LoginEvent.Builder, LoginEventOrBuilder>(
                  (LoginEvent) event_,
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        eventCase_ = 1;
        onChanged();;
        return loginEventBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          LogoutEvent, LogoutEvent.Builder, LogoutEventOrBuilder> logoutEventBuilder_;
      /**
       * <code>.LogoutEvent logoutEvent = 2;</code>
       * @return Whether the logoutEvent field is set.
       */
      @Override
      public boolean hasLogoutEvent() {
        return eventCase_ == 2;
      }
      /**
       * <code>.LogoutEvent logoutEvent = 2;</code>
       * @return The logoutEvent.
       */
      @Override
      public LogoutEvent getLogoutEvent() {
        if (logoutEventBuilder_ == null) {
          if (eventCase_ == 2) {
            return (LogoutEvent) event_;
          }
          return LogoutEvent.getDefaultInstance();
        } else {
          if (eventCase_ == 2) {
            return logoutEventBuilder_.getMessage();
          }
          return LogoutEvent.getDefaultInstance();
        }
      }
      /**
       * <code>.LogoutEvent logoutEvent = 2;</code>
       */
      public Builder setLogoutEvent(LogoutEvent value) {
        if (logoutEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          event_ = value;
          onChanged();
        } else {
          logoutEventBuilder_.setMessage(value);
        }
        eventCase_ = 2;
        return this;
      }
      /**
       * <code>.LogoutEvent logoutEvent = 2;</code>
       */
      public Builder setLogoutEvent(
          LogoutEvent.Builder builderForValue) {
        if (logoutEventBuilder_ == null) {
          event_ = builderForValue.build();
          onChanged();
        } else {
          logoutEventBuilder_.setMessage(builderForValue.build());
        }
        eventCase_ = 2;
        return this;
      }
      /**
       * <code>.LogoutEvent logoutEvent = 2;</code>
       */
      public Builder mergeLogoutEvent(LogoutEvent value) {
        if (logoutEventBuilder_ == null) {
          if (eventCase_ == 2 &&
              event_ != LogoutEvent.getDefaultInstance()) {
            event_ = LogoutEvent.newBuilder((LogoutEvent) event_)
                .mergeFrom(value).buildPartial();
          } else {
            event_ = value;
          }
          onChanged();
        } else {
          if (eventCase_ == 2) {
            logoutEventBuilder_.mergeFrom(value);
          }
          logoutEventBuilder_.setMessage(value);
        }
        eventCase_ = 2;
        return this;
      }
      /**
       * <code>.LogoutEvent logoutEvent = 2;</code>
       */
      public Builder clearLogoutEvent() {
        if (logoutEventBuilder_ == null) {
          if (eventCase_ == 2) {
            eventCase_ = 0;
            event_ = null;
            onChanged();
          }
        } else {
          if (eventCase_ == 2) {
            eventCase_ = 0;
            event_ = null;
          }
          logoutEventBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.LogoutEvent logoutEvent = 2;</code>
       */
      public LogoutEvent.Builder getLogoutEventBuilder() {
        return getLogoutEventFieldBuilder().getBuilder();
      }
      /**
       * <code>.LogoutEvent logoutEvent = 2;</code>
       */
      @Override
      public LogoutEventOrBuilder getLogoutEventOrBuilder() {
        if ((eventCase_ == 2) && (logoutEventBuilder_ != null)) {
          return logoutEventBuilder_.getMessageOrBuilder();
        } else {
          if (eventCase_ == 2) {
            return (LogoutEvent) event_;
          }
          return LogoutEvent.getDefaultInstance();
        }
      }
      /**
       * <code>.LogoutEvent logoutEvent = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          LogoutEvent, LogoutEvent.Builder, LogoutEventOrBuilder>
          getLogoutEventFieldBuilder() {
        if (logoutEventBuilder_ == null) {
          if (!(eventCase_ == 2)) {
            event_ = LogoutEvent.getDefaultInstance();
          }
          logoutEventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              LogoutEvent, LogoutEvent.Builder, LogoutEventOrBuilder>(
                  (LogoutEvent) event_,
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        eventCase_ = 2;
        onChanged();;
        return logoutEventBuilder_;
      }

      private int type_ = 0;
      /**
       * <code>.MessageType type = 3;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.MessageType type = 3;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MessageType type = 3;</code>
       * @return The type.
       */
      @Override
      public MessageType getType() {
        @SuppressWarnings("deprecation")
        MessageType result = MessageType.valueOf(type_);
        return result == null ? MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.MessageType type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MessageType type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserEvent)
    }

    // @@protoc_insertion_point(class_scope:UserEvent)
    private static final UserEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserEvent();
    }

    public static UserEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserEvent>
        PARSER = new com.google.protobuf.AbstractParser<UserEvent>() {
      @Override
      public UserEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserEvent> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserEvent> getParserForType() {
      return PARSER;
    }

    @Override
    public UserEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int64 sessionId = 2;</code>
     * @return The sessionId.
     */
    long getSessionId();

    /**
     * <code>optional string ip = 3;</code>
     * @return Whether the ip field is set.
     */
    boolean hasIp();
    /**
     * <code>optional string ip = 3;</code>
     * @return The ip.
     */
    String getIp();
    /**
     * <code>optional string ip = 3;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>int64 time = 4;</code>
     * @return The time.
     */
    long getTime();
  }
  /**
   * Protobuf type {@code LoginEvent}
   */
  public static final class LoginEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginEvent)
      LoginEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginEvent.newBuilder() to construct.
    private LoginEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginEvent() {
      name_ = "";
      ip_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginEvent();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              sessionId_ = input.readInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              ip_ = s;
              break;
            }
            case 32: {

              time_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LoginEventProtobuf.internal_static_LoginEvent_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LoginEventProtobuf.internal_static_LoginEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LoginEvent.class, Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSIONID_FIELD_NUMBER = 2;
    private long sessionId_;
    /**
     * <code>int64 sessionId = 2;</code>
     * @return The sessionId.
     */
    @Override
    public long getSessionId() {
      return sessionId_;
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile Object ip_;
    /**
     * <code>optional string ip = 3;</code>
     * @return Whether the ip field is set.
     */
    @Override
    public boolean hasIp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string ip = 3;</code>
     * @return The ip.
     */
    @Override
    public String getIp() {
      Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ip = 3;</code>
     * @return The bytes for ip.
     */
    @Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private long time_;
    /**
     * <code>int64 time = 4;</code>
     * @return The time.
     */
    @Override
    public long getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (sessionId_ != 0L) {
        output.writeInt64(2, sessionId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
      }
      if (time_ != 0L) {
        output.writeInt64(4, time_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sessionId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, time_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LoginEvent)) {
        return super.equals(obj);
      }
      LoginEvent other = (LoginEvent) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getSessionId()
          != other.getSessionId()) return false;
      if (hasIp() != other.hasIp()) return false;
      if (hasIp()) {
        if (!getIp()
            .equals(other.getIp())) return false;
      }
      if (getTime()
          != other.getTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionId());
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp().hashCode();
      }
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LoginEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LoginEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LoginEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoginEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoginEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LoginEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LoginEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LoginEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LoginEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginEvent)
        LoginEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LoginEventProtobuf.internal_static_LoginEvent_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LoginEventProtobuf.internal_static_LoginEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LoginEvent.class, Builder.class);
      }

      // Construct using LoginEventProtobuf.LoginEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";

        sessionId_ = 0L;

        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LoginEventProtobuf.internal_static_LoginEvent_descriptor;
      }

      @Override
      public LoginEvent getDefaultInstanceForType() {
        return LoginEvent.getDefaultInstance();
      }

      @Override
      public LoginEvent build() {
        LoginEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public LoginEvent buildPartial() {
        LoginEvent result = new LoginEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ip_ = ip_;
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LoginEvent) {
          return mergeFrom((LoginEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LoginEvent other) {
        if (other == LoginEvent.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getSessionId() != 0L) {
          setSessionId(other.getSessionId());
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000001;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LoginEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LoginEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long sessionId_ ;
      /**
       * <code>int64 sessionId = 2;</code>
       * @return The sessionId.
       */
      @Override
      public long getSessionId() {
        return sessionId_;
      }
      /**
       * <code>int64 sessionId = 2;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(long value) {
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sessionId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        
        sessionId_ = 0L;
        onChanged();
        return this;
      }

      private Object ip_ = "";
      /**
       * <code>optional string ip = 3;</code>
       * @return Whether the ip field is set.
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string ip = 3;</code>
       * @return The ip.
       */
      public String getIp() {
        Object ref = ip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string ip = 3;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 3;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 3;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        ip_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>int64 time = 4;</code>
       * @return The time.
       */
      @Override
      public long getTime() {
        return time_;
      }
      /**
       * <code>int64 time = 4;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LoginEvent)
    }

    // @@protoc_insertion_point(class_scope:LoginEvent)
    private static final LoginEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoginEvent();
    }

    public static LoginEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginEvent>
        PARSER = new com.google.protobuf.AbstractParser<LoginEvent>() {
      @Override
      public LoginEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginEvent> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LoginEvent> getParserForType() {
      return PARSER;
    }

    @Override
    public LoginEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LogoutEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LogoutEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int64 sessionId = 2;</code>
     * @return The sessionId.
     */
    long getSessionId();

    /**
     * <code>optional string ip = 3;</code>
     * @return Whether the ip field is set.
     */
    boolean hasIp();
    /**
     * <code>optional string ip = 3;</code>
     * @return The ip.
     */
    String getIp();
    /**
     * <code>optional string ip = 3;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>int64 time = 4;</code>
     * @return The time.
     */
    long getTime();
  }
  /**
   * Protobuf type {@code LogoutEvent}
   */
  public static final class LogoutEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LogoutEvent)
      LogoutEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogoutEvent.newBuilder() to construct.
    private LogoutEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogoutEvent() {
      name_ = "";
      ip_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new LogoutEvent();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogoutEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              sessionId_ = input.readInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              ip_ = s;
              break;
            }
            case 32: {

              time_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LoginEventProtobuf.internal_static_LogoutEvent_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LoginEventProtobuf.internal_static_LogoutEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LogoutEvent.class, Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSIONID_FIELD_NUMBER = 2;
    private long sessionId_;
    /**
     * <code>int64 sessionId = 2;</code>
     * @return The sessionId.
     */
    @Override
    public long getSessionId() {
      return sessionId_;
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile Object ip_;
    /**
     * <code>optional string ip = 3;</code>
     * @return Whether the ip field is set.
     */
    @Override
    public boolean hasIp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string ip = 3;</code>
     * @return The ip.
     */
    @Override
    public String getIp() {
      Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>optional string ip = 3;</code>
     * @return The bytes for ip.
     */
    @Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private long time_;
    /**
     * <code>int64 time = 4;</code>
     * @return The time.
     */
    @Override
    public long getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (sessionId_ != 0L) {
        output.writeInt64(2, sessionId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
      }
      if (time_ != 0L) {
        output.writeInt64(4, time_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sessionId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, time_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LogoutEvent)) {
        return super.equals(obj);
      }
      LogoutEvent other = (LogoutEvent) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getSessionId()
          != other.getSessionId()) return false;
      if (hasIp() != other.hasIp()) return false;
      if (hasIp()) {
        if (!getIp()
            .equals(other.getIp())) return false;
      }
      if (getTime()
          != other.getTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionId());
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp().hashCode();
      }
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LogoutEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogoutEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogoutEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogoutEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogoutEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogoutEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogoutEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LogoutEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LogoutEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LogoutEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LogoutEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LogoutEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LogoutEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LogoutEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LogoutEvent)
        LogoutEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LoginEventProtobuf.internal_static_LogoutEvent_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LoginEventProtobuf.internal_static_LogoutEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LogoutEvent.class, Builder.class);
      }

      // Construct using LoginEventProtobuf.LogoutEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";

        sessionId_ = 0L;

        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LoginEventProtobuf.internal_static_LogoutEvent_descriptor;
      }

      @Override
      public LogoutEvent getDefaultInstanceForType() {
        return LogoutEvent.getDefaultInstance();
      }

      @Override
      public LogoutEvent build() {
        LogoutEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public LogoutEvent buildPartial() {
        LogoutEvent result = new LogoutEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ip_ = ip_;
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LogoutEvent) {
          return mergeFrom((LogoutEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LogoutEvent other) {
        if (other == LogoutEvent.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getSessionId() != 0L) {
          setSessionId(other.getSessionId());
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000001;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LogoutEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LogoutEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long sessionId_ ;
      /**
       * <code>int64 sessionId = 2;</code>
       * @return The sessionId.
       */
      @Override
      public long getSessionId() {
        return sessionId_;
      }
      /**
       * <code>int64 sessionId = 2;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(long value) {
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sessionId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        
        sessionId_ = 0L;
        onChanged();
        return this;
      }

      private Object ip_ = "";
      /**
       * <code>optional string ip = 3;</code>
       * @return Whether the ip field is set.
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string ip = 3;</code>
       * @return The ip.
       */
      public String getIp() {
        Object ref = ip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string ip = 3;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 3;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 3;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        ip_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>int64 time = 4;</code>
       * @return The time.
       */
      @Override
      public long getTime() {
        return time_;
      }
      /**
       * <code>int64 time = 4;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LogoutEvent)
    }

    // @@protoc_insertion_point(class_scope:LogoutEvent)
    private static final LogoutEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LogoutEvent();
    }

    public static LogoutEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogoutEvent>
        PARSER = new com.google.protobuf.AbstractParser<LogoutEvent>() {
      @Override
      public LogoutEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogoutEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogoutEvent> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LogoutEvent> getParserForType() {
      return PARSER;
    }

    @Override
    public LogoutEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogoutEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogoutEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020LoginEvent.proto\"x\n\tUserEvent\022!\n\nlogin" +
      "Event\030\001 \001(\0132\013.LoginEventH\000\022#\n\013logoutEven" +
      "t\030\002 \001(\0132\014.LogoutEventH\000\022\032\n\004type\030\003 \001(\0162\014." +
      "MessageTypeB\007\n\005event\"S\n\nLoginEvent\022\014\n\004na" +
      "me\030\001 \001(\t\022\021\n\tsessionId\030\002 \001(\003\022\017\n\002ip\030\003 \001(\tH" +
      "\000\210\001\001\022\014\n\004time\030\004 \001(\003B\005\n\003_ip\"T\n\013LogoutEvent" +
      "\022\014\n\004name\030\001 \001(\t\022\021\n\tsessionId\030\002 \001(\003\022\017\n\002ip\030" +
      "\003 \001(\tH\000\210\001\001\022\014\n\004time\030\004 \001(\003B\005\n\003_ip*$\n\013Messa" +
      "geType\022\t\n\005LOGIN\020\000\022\n\n\006LOGOUT\020\001B\024B\022LoginEv" +
      "entProtobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserEvent_descriptor,
        new String[] { "LoginEvent", "LogoutEvent", "Type", "Event", });
    internal_static_LoginEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginEvent_descriptor,
        new String[] { "Name", "SessionId", "Ip", "Time", "Ip", });
    internal_static_LogoutEvent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LogoutEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogoutEvent_descriptor,
        new String[] { "Name", "SessionId", "Ip", "Time", "Ip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
