// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netty_rpc.proto

package com.tiger.rpc.common.protos;

public interface RpcParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.RpcParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>bytes value = 2;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
