// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netty_rpc.proto

package com.tiger.rpc.common.protos;

public interface RpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.RpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>optional string clazz = 2;</code>
   * @return Whether the clazz field is set.
   */
  boolean hasClazz();
  /**
   * <code>optional string clazz = 2;</code>
   * @return The clazz.
   */
  String getClazz();
  /**
   * <code>optional string clazz = 2;</code>
   * @return The bytes for clazz.
   */
  com.google.protobuf.ByteString
      getClazzBytes();

  /**
   * <code>optional bytes value = 3;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>optional bytes value = 3;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
